<!--* In JavaScript, the try...catch statement is used for error handling. It allows you to catch and handle exceptions (errors) that occur within a block of code. Here's how it works:

 <!--? try Block: The try block contains the code that you want to execute. It is the block of code where you anticipate that an error might occur. -->

<!--? catch Block: The catch block follows the try block and is used to catch any exceptions (errors) that occur within the try block. If an exception occurs, JavaScript jumps to the catch block to handle the error. The catch block takes an error object as a parameter, which can be used to access information about the error, such as its message or stack trace. -->

<!--? finally Block (Optional): The finally block, if provided, is executed regardless of whether an error occurs or not. It is typically used for cleanup tasks that should always be performed, such as closing resources or releasing locks. -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dad Jokes</title>
    <link rel="stylesheet" href="style.css" />
    <style>
      .container {
        background-color: rgb(255, 255, 255);
        text-align: center;
        padding: 2.4rem 6.4rem;
        border-radius: 0.6rem;
        color: #000;
        min-width: 32rem;
      }

      .api_body {
        font-size: 1.7rem;
        letter-spacing: 0.1rem;
        margin-bottom: 2rem;
        margin-top: 1rem;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>Welcome to Dad Jokes!</h1>
      <section class="api_body"></section>
      <button id="fetchJoke">Get Another Joke</button>
    </div>

    <script>
      const apiBody = document.querySelector(".api_body");
      const apiUrl = "https://icanhazdadjoke.com/";

      // async function fetchData() {

      // Add event listener to fetch a new joke when the button is clicked
    </script>
  </body>
</html>
